name: docs

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [created]


jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          sudo apt-get install pandoc
          python -m pip install flit
          FLIT_ROOT_INSTALL=1 flit install --deps develop
      - name: run sphinx
        run: |
          cd docs && make html
      - name: Get target folder from github ref
        run: |
          # get rid of "refs/"
          tmp_target_dir="${github_ref/refs\//}"
          echo $tmp_target_dir
          # when on master, we want to deploy to the root dir (-> empty string)
          target_dir="${tmp_target_dir/heads\/master/}
          echo $target_dir
          echo "::set-env name=target_dir::$target_dir"
        env:
          github_ref: ${{ github.ref }}
      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/_build/html # The folder the action should deploy.
          TARGET_FOLDER: $target_dir
          CLEAN: true
